### ISSUE TITLE
Fix the signature for PairUtil functions and add examples.

### ISSUE THREAD

**Issue by AmritKumar** [Zilliqa/scilla-docs#39]

**Comment by jjcnn** [comment]
More generally, we need examples of `TFun` and `TApp`, and we need to specify the order of the type variables in polymorphic functions, i.e., `fst : 'A => 'B => Pair 'A 'B -> 'A`.

**Comment by vaivaswatha** [comment]
@jjcnn can this be closed ? https://github.com/Zilliqa/scilla-docs/pull/66#issuecomment-514294084

**Comment by jjcnn** [comment]
> @jjcnn can this be closed ? [#66 (comment)](https://github.com/Zilliqa/scilla-docs/pull/66#issuecomment-514294084)

It would be nice if the example shows the result of applying `fst`. I'll take a look at it tomorrow.

**Comment by anton-trunov** [comment]
Let me close this issue for now, I think it's addressed in PR #114. Feel free to re-open if there is something else that needs to be done.
