### ISSUE TITLE
Use QA in docs

### ISSUE THREAD

**Issue by kenchangh** [Zilliqa/scilla-docs#42]
There should be a note in the docs that says the currency units in `_amount` are denominated in Qas. 

Hence, this is wrong:
```
let zils_per_tweet = Uint128 10
```

this is right:
```
let zils_per_tweet = Uint128 10000000000000
```

Places to change wordings:

Change from ZILs to QAs -
https://scilla.readthedocs.io/en/latest/scilla-in-depth.html#transitions

Change from ZILs to QAs -
https://scilla.readthedocs.io/en/latest/scilla-in-depth.html#transitions

Make the `goal` larger in init.json
https://scilla.readthedocs.io/en/latest/interface.html#example-2

Make values 10**12 in contract
https://scilla.readthedocs.io/en/latest/interface.html#interpreter-output
https://scilla.readthedocs.io/en/latest/interface.html#id2
https://scilla.readthedocs.io/en/latest/interface.html#id3

**Comment by benjixx** [comment]
I ran into the same issue today.
Although it is mentioned in https://scilla.readthedocs.io/en/latest/scilla-in-depth.html#units that the unit QA is used, this unit does not seem to be mentioned anywhere in the context of `_amount`.
